const iconTypes = {
    accessTime: "accessTime",
    add: "add",
    back: "back",
    business: "business",
    close: "close",
    dashboard: "dashboard",
    dataUsage: "dataUsage",
    delete: "delete",
    description: "description",
    download: "download",
    edit: "edit",
    events: "events",
    exit: "exit",
    login: "login",
    home: "home",
    left: "left",
    list: "list",
    logout: "logout",
    menu: "menu",
    more: "more",
    personAdd: "personAdd",
    personAddDisabled: "personAddDisabled",
    setDark: "setDark",
    setLight: "setLight",
    settings: "settings",
    stats: "stats",
    supervisedUser: "supervisedUser",
    upload: "upload",
    uploadCloud: "uploadCloud"
};

export default iconTypes;